# Generated by Django 5.1 on 2024-08-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('prioridad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Tipo Maestro',
                'verbose_name_plural': 'Tipos Maestros',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('prioridad', models.PositiveIntegerField()),
                ('tipomaestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos.tipomaestro')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
    ]
