# Generated by Django 5.1.1 on 2024-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaestro',
            name='in_main',
            field=models.BooleanField(default=True),
        ),
    ]
