# Generated by Django 5.1.2 on 2024-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0003_alter_tipomaestro_in_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomaestro',
            name='in_main',
        ),
        migrations.AddField(
            model_name='tipo',
            name='in_main',
            field=models.BooleanField(default=False, verbose_name='En Main'),
        ),
    ]
