# Generated by Django 5.1.1 on 2024-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='prioridad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
